import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HomeLogoLink } from "@/components/home-logo-link";
import { Konami } from "@/components/konami";
import { PageTransition } from "@/components/page-transition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://vc-billingsley.com"),
  title: {
    default: "V.C. Billingsley",
    template: "%s — V.C. Billingsley",
  },
  description: "V.C. Billingsley — design & code, San Francisco.",
  openGraph: {
    type: "website",
    siteName: "V.C. Billingsley",
    title: "V.C. Billingsley",
    description: "Design & code, San Francisco.",
    url: "https://vc-billingsley.com",
    // The image itself is generated by `src/app/opengraph-image.tsx`;
    // Next.js wires that route into the metadata automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: "V.C. Billingsley",
    description: "Design & code, San Francisco.",
    creator: "@verycracked",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-dvh overflow-hidden antialiased`}
    >
      <body className="h-dvh overflow-hidden bg-bg">
        {/* The bordered content card is pinned to the viewport via fixed
            positioning so it can't ever scroll out of frame. Inside it,
            a flex column reserves space for the (fixed) chrome and gives
            the remaining area to a single scroll region. */}
        <div className="fixed inset-2 z-0">
          <div className="page-dissolve double-stroke relative flex h-full flex-col overflow-hidden rounded-[8px] bg-content">
            {/* Top-leftmost wordmark, anchored to the card so it stays
                visible while the inner area scrolls. Doubles as a scroll-
                to-top control when already on `/`. */}
            <HomeLogoLink />
            <div
              id="app-scroll"
              className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden"
            >
              <PageTransition>{children}</PageTransition>
            </div>
            <Konami />
          </div>
        </div>
      </body>
    </html>
  );
}
